### ISSUE TITLE
Word batch installs BUT ImportError for FTRL 

### ISSUE THREAD

**Issue by Shanth1984** [anttttti/Wordbatch#11]
Hi 

I installed wordbatch on MacOSX Sierra using PIP. The installation was successful. The following commands work in Jupyter notebook 

import wordbatch
from wordbatch.extractors import WordBag, WordHash

However importing FTRL gives an Import errror (screen shot attached).
from wordbatch.models import FTRL

Please advise. 

Regards
Shanth

<img width="1440" alt="screen shot 2018-02-25 at 4 02 32 pm" src="https://user-images.githubusercontent.com/33072081/36640487-be3b1318-1a45-11e8-8ffe-3d31f3ec70aa.png">

**Comment by Shanth1984** [comment]
Hi 

Any updates suggestions on this?

Regards
Shanth

**Comment by sophie-greene** [comment]
I suggest posting the entire error message. sometimes the most telling part of a message is its end.

**Comment by anttttti** [comment]
You need GCC compiler on your OS, supporting the OpenMP c-level multithreading. Linking gcc calls to another compiler, or having GCC-incompatible compiler arguments will cause these issues.
