### ISSUE TITLE
cannot install on windows 8.1

### ISSUE THREAD

**Issue by goldentom42** [anttttti/Wordbatch#13]
Hi @anttttti, thanks for your great package and congrats for your 5th place in Mercair !
I'm trying to get wordbatch to work on my own PC (kaggle kernels are great but I prefer getting things done locally ;), however I can't seem to get the pip installtion right.

I'm using Anaconda with python 3.6 and VC++ build tools 2015 installed

Here is the full installation output :

>pip install wordbatch
Collecting wordbatch
  Using cached Wordbatch-1.3.0.tar.gz
Requirement already satisfied: cython in c:\users\olivier\anaconda3\lib\site-packages (from wordbatch)
Requirement already satisfied: scikit-learn in c:\users\olivier\anaconda3\lib\site-packages (from wordbatch)
Requirement already satisfied: python-Levenshtein in c:\users\olivier\anaconda3\lib\site-packages (from wordbatch)
Requirement already satisfied: py-lz4framed in c:\users\olivier\anaconda3\lib\site-packages (from wordbatch)
Requirement already satisfied: setuptools in c:\users\olivier\anaconda3\lib\site-packages (from python-Levenshtein->wordb
atch)
Building wheels for collected packages: wordbatch
  Running setup.py bdist_wheel for wordbatch ... error
  Complete output from command C:\Users\olivier\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\olivier\\AppData\\Local\\Temp\\pip-build-0xefvztp\\wordbatch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\olivier\AppData\Local\Temp\tmp7rkq7xj6pip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\wordbatch
  copying wordbatch\wordbatch.py -> build\lib.win-amd64-3.6\wordbatch
  copying wordbatch\__init__.py -> build\lib.win-amd64-3.6\wordbatch
  creating build\lib.win-amd64-3.6\wordbatch\extractors
  copying wordbatch\extractors\__init__.py -> build\lib.win-amd64-3.6\wordbatch\extractors
  creating build\lib.win-amd64-3.6\wordbatch\models
  copying wordbatch\models\__init__.py -> build\lib.win-amd64-3.6\wordbatch\models
  running build_ext
  error: [WinError 2] The system cannot find the file specified

  ----------------------------------------
  Failed building wheel for wordbatch
  Running setup.py clean for wordbatch
Failed to build wordbatch
Installing collected packages: wordbatch
  Running setup.py install for wordbatch ... error
    Complete output from command C:\Users\olivier\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\U
sers\\olivier\\AppData\\Local\\Temp\\pip-build-0xefvztp\\wordbatch\\setup.py';f=getattr(tokenize, 'open', open)(__file__)
;code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\olivier\A
ppData\Local\Temp\pip-07pzlhjs-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\wordbatch
    copying wordbatch\wordbatch.py -> build\lib.win-amd64-3.6\wordbatch
    copying wordbatch\__init__.py -> build\lib.win-amd64-3.6\wordbatch
    creating build\lib.win-amd64-3.6\wordbatch\extractors
    copying wordbatch\extractors\__init__.py -> build\lib.win-amd64-3.6\wordbatch\extractors
    creating build\lib.win-amd64-3.6\wordbatch\models
    copying wordbatch\models\__init__.py -> build\lib.win-amd64-3.6\wordbatch\models
    running build_ext
    error: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command "C:\Users\olivier\Anaconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\olivier\\AppData\\Local\\Temp\\pip-build-0xefvztp\\wordbatch\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\olivier\AppData\Local\Temp\pip-07pzlhjs-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\olivier\AppData\Local\Temp\pip-build-0xefvztp\wordbatch\

Would you have any idea?
Thanks.

**Comment by anttttti** [comment]
Pip version is still 1.3.0, and this had problems installing on Windows. There's been fixes after Mercari, including the Windows install. If you clone the repo and build it with "python setup.py install", it should work.

**Comment by goldentom42** [comment]
@anttttti, thanks for your swift reply. I'll try to do a new checkout to get the latest changes and try a new setup install. Hopefully that will work (fingers crossed)

**Comment by goldentom42** [comment]
Just dropped the old folder and did a git clone to get the latest modifications but I still get:

running build_ext
error: [WinError 2] The system cannot find the file specified

__init__.py files are correctly copied to the build folder. The problem is windows does not tell me which file it does not find, that would be too simple I guess ;-)

I'll try to check my cython book to see if I can build all ocrrectly locally (without package installation)

**Comment by goldentom42** [comment]
Just opened a command window on windows 8.1, types pip install wordbatch and it installed ! And it installs 1.3.0.

I also cloned the repo and typed python setup.py install and it installed 1.3.5.

Since my last comment I've installed VS2017 but not sure it had an impact.

Anyway I can close this Issue. Thanks.
