### ISSUE TITLE
Licensing for commercial use without open source?

### ISSUE THREAD

**Issue by peterhurford** [anttttti/Wordbatch#18]
This is an amazing library and I'd like to use it for some commercial work, but we're not able to satisfy the GNU GPL conditions of stating changes or disclosing source. Would you be willing to distribute under an MIT, Apache, or BSD license so that we could use this work?

**Comment by anttttti** [comment]
I could reconsider the licensing at some point. With GPL2 you can still use it commercially and sell products with the package, but it imposes some incentive to contribute core improvements back to the community. 

The package is also becoming increasingly modular and sklearn-compatible. So you can mix parts of the package and sklearn freely, and write components such as transformer classes without giving those back to open source, or changing the core parts.
