### ISSUE TITLE
Tried to pickle the fitted wordbatch model, but bumped into this Error: AttributeError: 'function' object has no attribute 'im_self'

### ISSUE THREAD

**Issue by marsan-ma** [anttttti/Wordbatch#19]
Thanks for this great work, hopefully this could incrementally importing all the NLP feature extraction tricks!

I tried to pickle the fitted model for future testing data, but bumped into this Error which says:

wordbatch/extractors/extractors.pyx in wordbatch.extractors.extractors._pickle_method()
AttributeError: 'function' object has no attribute 'im_self'

**Comment by anttttti** [comment]
Looks like some of the pickling code is left incomplete. If you can give more details on what object you tried to pickle, that could help solving this. The error is coming from a extractors.pyx, but you mention this came from unpickling a model, which I assume was FM_FTRL or one of the other models.

**Comment by anttttti** [comment]
Changed to pickling with dill, so batcher can now handle these cases
