### ISSUE TITLE
from wordbatch.data_utils import *

### ISSUE THREAD

**Issue by suresh-chinta** [anttttti/Wordbatch#23]
Hi, I am getting an error when I access wordbatch.data_utils, can you please help.

ImportError                               Traceback (most recent call last)
<ipython-input-10-f8f081583d75> in <module>()
      9 import gc
     10 from contextlib import contextmanager
---> 11 from wordbatch.data_utils import *

ImportError: No module named 'wordbatch.data_utils'

**Comment by suresh-chinta** [comment]
I have tried this :+1: 
pip install git+https://github.com/anttttti/Wordbatch.git@1.3.3

with error:

File "/home/xxx/anaconda/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-2-f8f081583d75>", line 11, in <module>
    from wordbatch.data_utils import *

  File "/home/xxx/anaconda/lib/python3.5/site-packages/wordbatch/data_utils.py", line 13
    print(f'[{name}] done in {time.time() - t0:.0f} s')
                                                     ^
SyntaxError: invalid syntax

**Comment by tingjiaqi123** [comment]
maybe you can try to update python version to 3.6

**Comment by anttttti** [comment]
Update to version >=1.3.5
