### ISSUE TITLE
Multiprocessing Hanging in Python 3.6+

### ISSUE THREAD

**Issue by canivel** [anttttti/Wordbatch#27]
Hi, I'm building a very simple test script in jupyter using your own example dataset Tweets.csv with the same preprocessing and normalization.

If I use method="serial", it runs at the same time no error, but if I change to multiprocessing it hangs and stay there forever, does not matter the size of the corpus...

I'm pretty sure there is no error at the corpus since serial runs ok... looks like there is some lock or limit for multiprocessing in windows... I'm researching it, if you have any fix please let me know.

**Comment by canivel** [comment]
Well i found ... it does not work inside jupyter because it need to run directly , In short, the subprocesses do not know they are subprocesses and are attempting to run the main script recursively. 
So don't use jupyter for multiprocessing ...

**Comment by canivel** [comment]
The strange is if I execute from the command line it works flawless with multiprocessing... I've 128gb ram locally, and the max consumption that i tested was a matrix of (3672320, 8388608) that took 25gb of ram and 70 secs to execute with 8 procs from the command line...

From jupyter even if I try the (14345, 8388608) matrix it goes no where with multiprocessing, but works with serial...

**Comment by canivel** [comment]
maybe is something like this
https://github.com/jupyter/notebook/issues/1703

**Comment by M-Harrington** [comment]
@anttttti I've reproduced the error using a very simple function.  It does seem to be a problem with Windows and Jupyter. It's not clear to me as to why it does not work.  I've  posted my short example in a stackoverflow post [here](https://stackoverflow.com/questions/57103984/why-cant-jupyter-notebooks-handle-multiprocessing-on-windows).

**Comment by anttttti** [comment]
> @anttttti I've reproduced the error using a very simple function. It does seem to be a problem with Windows and Jupyter. It's not clear to me as to why it does not work. I've posted my short example in a stackoverflow post [here](https://stackoverflow.com/questions/57103984/why-cant-jupyter-notebooks-handle-multiprocessing-on-windows).

Thanks for reporting this. Strange that Jupyter does that. With Wordbatch 1.4 you can try Dask, Ray, Spark or Loky as an alternative backend, to see if those better with Jupyter.

**Comment by nelsonperry** [comment]
Hi.
I would just like to add, as a fairly novice programmer, that I experience exactly the same problem on Linux *Ubuntu and Mint*
when using the python wrapper **Idle**. Programmes using the multiprocessing module just hang for ever - even CTRL-C will not interrupt the endless loop.
However, running Python from the command line gives flawless execution.
I have had exactly the same frustrations when writing bits of code using the **Curses** module. They work fine from the command line but will not run in IDLE.
The reason, I think, is although it  _looks_ as though the IDLE window (and I guess Jupyter too -though I've not used that ) is some kind of terminal window, in fact it is no such thing and the overheads in having this so-called user-friendly environment are stopping Python from its usual memory management tasks.

Moral of the story: Stick to a basic editor and the command line.
