### ISSUE TITLE
'tuple' object has no attribute 'transform'

### ISSUE THREAD

**Issue by JuberGandharv** [anttttti/Wordbatch#32]
hello i m using following code to transform features:

wb.fit(X_train_with_new_feature['name'].tolist())
X_train_name_wordbatch = wb.transform(X_train_with_new_feature['name'].tolist())

but keep getting error " 'tuple' object has no attribute 'transform' "

can anyone help me?

**Comment by anttttti** [comment]
how did you define wb?  looks like "wb.transform()" fails. give a more complete example of the code.

**Comment by rabiraj** [comment]
WordBatch(extractor=
                            (WordHash, {"input":"filename", "encoding":"utf-16", "lowercase":True, 
                            "strip_accents":"ascii", "analyzer":'word', "n_features":2 ** 18}),
                            batcher=Batcher(backend="loky")
                       )

**Comment by anttttti** [comment]
Defining the extractor objects for the WordBatch pipeline was changed from earlier versions. 

Instead of this:
```
WordBatch(extractor=(WordHash, {"n_features":2 ** 18}))
```
Use:
```
WordBatch(extractor=WordHash(n_features=2 ** 18))
```
So instead of giving the arguments for the pipeline to construct the object, you pass the constructed object itself. The earlier way to define extractor objects was unconventional.
