### ISSUE TITLE
Can I add documentation for you?

### ISSUE THREAD

**Issue by JanzenLiu** [anttttti/Wordbatch#6]
Hey dude, this library is amazing and I like it very much. Can I write documentation for it? I have gone through some of the codes in the process of using it and understanding it. I think such a great work will be greater with a documentation. Maybe we can collaborate?

Waiting for your reply : )

**Comment by anttttti** [comment]
Of course. Thanks for the offer.

I'll do a code clean up after the Mercari competition closes this week. This includes fixing bugs, and removing differences to sklearn API, for example how .fit() and .transform() behave.

**Comment by JanzenLiu** [comment]
Sure thanks. I would also start working on this after the competition ends. Besides, Are you interested in adding BM25 module? i.e. similar to WordBag but the score of each word for each document is BM25 score, it seems better than simple TF-IDF.

**Comment by anttttti** [comment]
We can do this, it won't be difficult to add. Average document lengths need to be tracked for the BM25 document length normalization, but that's all. BM25 IDF is applied the same as in TF-IDF, it's only the term+length normalization that works different. 

Argument options for TF-IDF/BM25 configurations can get messy, so those need to be sorted out. One option would be refactoring the normalizations into a separate class, that could be used on any set of sparse matrix features.

**Comment by JanzenLiu** [comment]
That's great. By the way how can I contact you except through Github? I will be better if we can contact more instantly. My email is chengtsung_liu@yahoo.com, and if you use Facebook or something else it will also be okay for me.
